[package]
name = "mccs-caps"
version = "0.0.1"
authors = ["arcnmx"]

description = "MCCS capability string parser"
keywords = ["ddc/ci", "mccs", "vcp", "vesa"]

documentation = "http://arcnmx.github.io/mccs-rs/mccs_caps"
repository = "https://github.com/arcnmx/mccs-rs"
readme = "../README.md"
license = "MIT"

[badges]
travis-ci = { repository = "arcnmx/mccs-rs" }
maintenance = { status = "passively-maintained" }

[dependencies]
nom = "^3.2.1"
mccs = { version = "^0.0.1", path = "../" }
